### ISSUE TITLE
Realm and presenter

### ISSUE THREAD

**Issue by gugakatsi** [NileshJarad/android-mvp-material-and-realm#1]
As i saw in presenter , there was directly getting Realm instance as an argument, is it normal? is realm still counts as part of pure java and not android. thanks in advance.

**Comment by NileshJarad** [comment]
@gugakatsi Realm is not Pure java part. For more information visit this link https://github.com/realm/realm-java/issues/3750

**Comment by gugakatsi** [comment]
@NileshJarad so if it's not why use it in presenter, as far as i know best is to use pure java stuff only in presenter ,
